### ISSUE TITLE
[meta] Migrate remaining `*Data.json` files from KumaScript into the `mdn‑data` package

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#1378]
## User story
As a MDN contributor, I want to have the data in a centralised place, so I know where to contribute data, which is then displayed in MDN pages.

## Acceptance criteria
All `*Data.json` files have been migrated from KumaScript to `mdn‑data`.

## Tasks
- [ ] Migrate `InterfaceData.json` (#1694)
- [ ] Migrate `GroupData.json`
- [ ] Migrate `SpecData.json` (https://github.com/mdn/data/pull/397, https://github.com/mdn/kumascript/pull/1283)
- [ ] Migrate `SVGData.json`

## See also
- [bug 1571626](https://bugzilla.mozilla.org/show_bug.cgi?id=1571626)

---

/cc @a2sheppy, @atopal, @chrisdavidmills, @davidflanagan, @Elchi3, @escattone, @teoli2003, @wbamberg
