### ISSUE TITLE
KumaScript: Use `inheritance.json` from the `mdn‑data` package

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#1379]
Part of #1695

## User story
As a MDN contributor, I want to have the data in a centralised place, so I know where to contribute data, which is then displayed in MDN pages.

## Acceptance criteria
API interface inheritance data is used from the `mdn‑data` package within **KumaScript** and `InterfaceData.json` is deleted.

## Tasks
- [x] https://github.com/mdn/data/pull/122 (initial import by @teoli2003)
- [x] https://github.com/mdn/data/pull/358: Sort `mdn‑data/api/inheritance.json`
- [x] https://github.com/mdn/data/pull/371: Import remaining `InterfaceData.json` changes from KumaScript
- [ ] https://github.com/mdn/kumascript/pull/1178: Use `inheritance.json` from the `mdn‑data` package

## See also
- [bug 1571627](https://bugzilla.mozilla.org/show_bug.cgi?id=1571627)

---

/cc @a2sheppy, @atopal, @chrisdavidmills, @davidflanagan, @Elchi3, @escattone, @teoli2003, @wbamberg
